scinage/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
import django_cas_ng.views
import haystack.urls
import layers
from layers import views as views
from layers import dashboard as dashboard
from rest_framework import routers
from layers.api import *

#Register api paths
router = routers.SimpleRouter()
router.register(r'layer', LayerAPIViewset, base_name='layer')

handler404 = layers.views.handler404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', layers.dashboard.dashboard_all, name="dashboard"),
    url(r'^$', layers.views.frontpage, name="home"),
    url(r'^uploadimage/$', layers.views.ajaximage, name="upload_image"),
    url(r'^uploadvideo/$', layers.views.ajaxvideo, name="upload_video"),

    # Layer Editing
    url(r'^extracontrols/$', layers.views.controlsExtra, name="extra_controls"),
    url(r'^versionfeedback/(?P<version_id>\d+)/$', layers.views.versionFeedback, name="version_feedback"),

    url(r'^widgets/search/', include('haystack.urls')),
    url(r'^widgets/$', layers.views.manageLayers, name="layers"),
    url(r'^widgets/list/(?P<mode>\w+)/$', layers.views.listLayers, name="list_layers"),
    url(r'^widgets/new/$', layers.views.editLayernew, name="new_layer"),
    url(r'^widgets/clone/(?P<layer_id>\d+)/$', layers.views.cloneLayer, name="clone_layer"),
    url(r'^widgets/edit/(?P<layer_id>\d+)/$', layers.views.editLayernew, name="edit_layer"),
    url(r'^widgets/delete/(?P<layer_id>\d+)/$', layers.views.deleteLayer, name="delete_layer"),
    url(r'^widgets/view/(?P<layer_id>\d+)/$', layers.views.editLayer, name="view_layer"),
    url(r'^widgets/editorinput/(?P<id>\d+)/$', layers.views.loadInput),
    url(r'^widgets/favlayer/$', layers.views.toggleLayerFav, name='favlayer'),
    url(r'^widgets/offlayer/$', layers.views.toggleLayerOff, name='offlayer'),
    url(r'^widgets/ratelayer/$', layers.views.layerRating, name='ratelayer'),
    url(r'^widgets/documentation/(?P<version_id>\d+)/$', layers.views.layerDocumentation, name='documentation'),

    url(r'^widgets/newedit/$', layers.views.editLayernew, name="edit_layer_new_new"),
    url(r'^widgets/newedit/(?P<layer_id>\d+)/$', layers.views.editLayernew, name="edit_layer_new"),

    url(r'^widgets/changelog/$', layers.views.changeLog, name="layer_change_log"),

    # Slide Editing
    url(r'^slides/$', layers.views.manageSlides, name="slides"),
    url(r'^slides/list/(?P<mode>\w+)/$', layers.views.listSlides, name="list_slides"),
    url(r'^slides/new/$', layers.views.editSlide, name="new_slide"),
    url(r'^slides/clone/(?P<slide_id>\d+)/$', layers.views.cloneSlide, name="clone_slide"),
    url(r'^slides/edit/(?P<slide_id>\d+)/$', layers.views.editSlide, name="edit_slide"),
    url(r'^slides/delete/(?P<slide_id>\d+)/$', layers.views.deleteSlide, name="delete_slide"),
    url(r'^slides/layersettings/(?P<version_id>\d+)/$', layers.views.layerSettings),
    url(r'^slides/layerjson/new/(?P<version_id>\d+)/$', layers.views.newLayerJson),
    url(r'^slides/layerpreview/$', layers.views.previewLayer),

    # Slide Viewing
    url(r'^slides/view/(?P<slide_id>\d+)/$', layers.views.viewSlide, name="view_slide"),


    # Slideshow Viewing
    url(r'^slideshows/$', layers.views.manageSlideshows, name="slideshows"),
    url(r'^slideshows/list/(?P<mode>\w+)/$', layers.views.listSlideshows, name="list_slideshows"),
    url(r'^slideshows/pdf/upload/$', layers.views.uploadPDF, name="upload_pdf"),
    url(r'^slideshows/pdf/$', layers.views.createSlideshowPDF, name="create_slideshow_from_pdf"),
    url(r'^slideshows/new/$', layers.views.editSlideshow, name="new_slideshow"),
    url(r'^slideshows/clone/(?P<slideshow_id>\d+)/$', layers.views.cloneSlideshow, name="clone_slideshow"),
    url(r'^slideshows/edit/(?P<slideshow_id>\d+)/$', layers.views.editSlideshow, name="edit_slideshow"),
    url(r'^slideshows/delete/(?P<slideshow_id>\d+)/$', layers.views.deleteSlideshow, name="delete_slideshow"),
    url(r'^slideshows/nextslide/(?P<slideshow_id>\d+)/(?P<current_index>\d+)/$', layers.views.nextSlide),
    url(r'^slideshows/view/(?P<slideshow_id>\d+)/$', layers.views.viewSlideshow, name="view_slideshow"),


    # Screen Viewing
    url(r'^screens/$', layers.views.manageScreens, name="screens"),
    url(r'^screens/list/$', layers.views.listScreens, name="list_screens"),
    url(r'^screens/new/$', layers.views.editScreen, name="new_screen"),
    url(r'^screens/edit/(?P<screen_id>\d+)/$', layers.views.editScreen, name="edit_screen"),
    url(r'^screens/delete/(?P<screen_id>\d+)/$', layers.views.editScreen, name="delete_screen"),
    url(r'^screens/view/(?P<slug>[-\w\d]+)/$', layers.views.viewScreen, name="view_screen"),
    url(r'^screens/view/(?P<slug>\d]+)/$', layers.views.viewScreen, name='view_screen_id'),
    url(r'^screens/ping/(?P<slug>[-\w\d]+)/$', layers.views.pingScreen, name="ping_screen"),



    # Group stuff
    url(r'^groups/$', layers.views.manageGroups, name="groups"),
    url(r'^groups/list/(?P<mode>\w+)/$', layers.views.listGroups, name="list_groups"),
    url(r'^groups/new/$', layers.views.editGroup, name="new_group"),
    url(r'^groups/edit/(?P<group_id>\d+)/$', layers.views.editGroup, name="edit_group"),
    url(r'^groups/view/(?P<group_id>\d+)/$', layers.views.viewGroup, name="view_group"),
    url(r'^groups/delete/(?P<group_id>\d+)/$', layers.views.editGroup, name="delete_group"),

    #Images
    url(r'^images/$', layers.views.images, name="images"),
    url(r'^image-upload/$', layers.views.imageUpload, name="image_upload"),
    url(r'^images/delete/(?P<id>[0-9]+)/$', layers.views.deleteImage, name="image_delete"),

    #Videos
    url(r'^videos/$', layers.views.videos, name="videos"),
    url(r'^video-upload/$', layers.views.videoUpload, name="video_upload"),
    url(r'^videos/delete/(?P<id>[0-9]+)/$', layers.views.deleteVideo, name="video_delete"),

    # Sharing
    url(r'^share/(?P<item>\w+)/(?P<pk>\d+)/$', layers.views.shareSettings, name="sharesettings"),
    url(r'^transfer/(?P<item>\w+)/(?P<pk>\d+)/$', layers.views.transferOwnership, name="transfer"),

    #trashbin
    url(r'^trashbin/$', layers.views.trashbin, name='trashbin'),
    url(r'^trashbin/delete/(?P<model>\w+)/(?P<id>[0-9]+)/$', layers.views.delete, name='delete'),
    url(r'^trashbin/restore/(?P<model>\w+)/(?P<id>[0-9]+)/$', layers.views.restore, name='restore'),

    #API routes
    # url(r'^api/', include(router.urls, namespace="api")),

]

from django.conf import settings

# Handling authentication routes

# We want to have the option for a CAS (Central Authentication System) to be configured

# We check for the prescene of a CAS_SERVER_URL in settings
# If it is present we will authenticate through that CAS Server
# Likewise, if it's not then we will use our own authentication system
if settings.CAS_SERVER_URL is not None:
    urlpatterns.extend([
        url(r'^accounts/login/$', django_cas_ng.views.LoginView.as_view(), name='login'),
        url(r'^accounts/logout/$', django_cas_ng.views.LogoutView.as_view(), name='logout')
    ])
else:
    urlpatterns.extend([
        url(r'^accounts/signup/$', layers.views.SignUp.as_view(), name='signup'),
        url('^', include('django.contrib.auth.urls')),
        # url(r'^accounts/password_reset/$', layers.views.PasswordReset.as_view(), name='password_reset'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
    ])

from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/media/', document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError, MaxValueValidator, MinValueValidator

from django.db.models.deletion import Collector
from django.db.models.fields.related import ForeignKey

from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill

from taggit.managers import TaggableManager
from haystack import signals

# Trashbin imports
from django.utils.translation import ugettext_lazy as _
try:
    from django.utils import timezone as datetime
except ImportError:
    from datetime import datetime

# Template Rendering with jinja
from jinja2 import Template

from .managers import *

# Input stuff
from .InputList import *


# For setting min max values on integerfields
class IntegerRangeField(models.IntegerField):
    def __init__(
        self,
        verbose_name=None,
        name=None,
        min_value=None,
        max_value=None,
        **kwargs
    ):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


# django-undelete models fixed
class TrashableMixin(models.Model):
    trashed_at = models.DateTimeField(
        _('Trashed'),
        editable=False,
        blank=True,
        null=True
    )

    objects = NonTrashedManager()
    trash = TrashedManager()
    everything = models.Manager()

    def delete(self, *args, **kwargs):
        # keyword argument trash has default value True
        trash = kwargs.get('trash', True)
        if not self.trashed_at and trash:
            self.trashed_at = datetime.now()
            self.save()
        else:
            super(TrashableMixin, self).delete(*args, **kwargs)

    def restore(self, commit=True):
        self.trashed_at = None
        if commit:
            self.save()

    class Meta:
        abstract = True


"""
When a user creates a new layer, it will create a version to go with it.
Anytime a user wants to change what their layer looks like, it will create a
new version for the revision, and (if it is not shared) offer to delete
older versions.

A version is simply a list of input types and the jinja2(?) html code to render
the object

Input types will each contain html / css / js to add an extra field for users
to fill in.
We'll have colorpickers and shit.
"""
variable = RegexValidator(
    r'^[a-zA-Z]{1}[0-9a-zA-Z_]*$',
    'Only alphanumeric characters are allowed. Must start with a letter.',
)


class UploadedImage(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(
        upload_to='uploaded_images',
        processors=[ResizeToFit(1920, 1080, False)],
        format='PNG',
        options={'quality': 80}
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFit(100, 100)],
        format='JPEG',
        options={'quality': 60}
    )


class UploadedVideo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    video = models.FileField(
        upload_to='uploaded_videos',
    )
    # title = models.CharField(max_length=255, blank=True)
    # thumbnail = ImageSpecField(
    #     source='video',
    #     processors=[ResizeToFit(100, 100)],
    #     format='JPEG',
    #     options={'quality': 60}
    # )


class Layer(TrashableMixin):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    shared = models.BooleanField(default=False)
    official = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    short = models.CharField(max_length=12)
    description = models.TextField()
    tags = TaggableManager()
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)
    documentation = models.TextField(blank=True)

    # tags
    icon = ProcessedImageField(
        upload_to='icons',
        processors=[ResizeToFit(72, 72)],
        format='PNG',
        options={'quality': 80},
        blank=True, null=True
    )

    def bleeding_edge(self):
        pass

    def latest(self):
        try:
            return self.version_set.filter(publish=True).order_by(
                '-creation_date'
            )[0:1].get()
        except:
            return self.version_set.order_by('-creation_date')[0:1].get()

    def uses(self):
        return SlideLayer.objects.filter(version__layer=self).count()

    def get_slides(self):
        return SlideLayer.objects.filter(version__layer=self).values("slide")

    def favs(self):
        return self.favoritelayer_set.all().count()

    @property
    def rating(self):
        return round(self.layerrating_set.aggregate(
            models.Avg('rating'))['rating__avg'],
            1
        )

    def clone(self, user):
        newlayer = Layer.objects.get(id=self.id)
        newlayer.id = None
        newlayer.public = False
        newlayer.official = False
        newlayer.title = "CLONE OF %s" % self.title
        newlayer.owner = user
        newlayer.publish = False
        newlayer.changes = 'First version.'
        newlayer.shared = False
        newlayer.save()
        for x in self.tags.all():
            newlayer.tags.add(x)
        newlayer.save()
        # And make the version...
        oldversion = self.latest()
        newversion = self.latest()
        newversion.publish = False
        newversion.id = None
        newversion.layer = newlayer
        newversion.save()
        for control in oldversion.control_set.all():
            newcontrol = Control(
                version=newversion,
                title=control.title,
                variable_name=control.variable_name,
                verbose=control.verbose,
                input_type=control.input_type,
                default=control.default
            )
            newcontrol.save()
        return newlayer


class FavoriteLayer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)


class LayerRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    rating = IntegerRangeField(min_value=1, max_value=5)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta():
        unique_together = ('user', 'layer')


class Version(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    content = models.TextField()
    content_css = models.TextField(blank=True)
    content_js = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)

    # every edit after a publish will be a new version!

    last_edit = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='version_last_edit',
        on_delete=models.CASCADE
    )

    def save(self, publish=False, *args, **kwargs):
        if self.layer.version_set.all().count() == 0:
            new_layer = True
        else:
            new_layer = False

        super(Version, self).save(*args, **kwargs)
        if publish is True and new_layer is False:
            # We're going to do this by hand because stackoverflow only has
            # answers for ancient versions of django and I spent too bloody
            # long trying to write a general duplicator and got only nonsense
            # error messages
            # Duplicate the object to make a new HEAD version.
            new = Version(
                layer=self.layer,
                content=self.content,
                content_css=self.content_css,
                content_js=self.content_js
            )
            new.save()
            # Get all the controls too
            for control in self.control_set.all():
                newcontrol = Control(
                    version=new,
                    title=control.title,
                    variable_name=control.variable_name,
                    verbose=control.verbose,
                    input_type=control.input_type,
                    default=control.default
                )
                newcontrol.save()

    def updateAvailable(self):
        return self.layer.version_set.filter(
            creation_date__gt=self.creation_date,
            publish=True
        ).order_by('-creation_date').first()

    def compileContent(self, data=None):
        from helpers.extra import extra_globals
        compiled = """
            <html>
                <head>
                    <style>
                        %s
                    </style>
                </head>
                <body>
                    %s
                    <script>
                        window.$ = $ || window.top.$
                        parent.iframeCheck()
                        $(window).on('load', function(){
                          parent.iframeCheck(true)
                        })
                    </script>
                    <script>

                        %s
                    </script>
                </body>
            </html>
        """ % (self.content_css, self.content, self.content_js)
        template = Template(compiled)
        template.globals.update(extra_globals)

        if not data:

templates/groups/editgroup.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Groups' 'groups' %}
	{% if group != None %}
	{% with "Edit: "|add:group.title as current %}
		{% breadcrumb current %}
	{% endwith %}
	{% else %}
    {% breadcrumb 'New Group' %}
    {% endif %}
{% endblock %}

{% block style %}

<style>
#controls_container tr>td:last-of-type,
#controls_container tr>th:last-of-type {
	border-left: solid 1px #DDDDDD;
}
#controls_container thead th:last-of-type {
	color: #a94442;
}
button:disabled {
	cursor: not-allowed;
}
.can_edit_permissions, .can_edit_permissions-head{
	{% if not owner %}
	display: none !important;
	{% else %}
	border-right: solid 1px #DDDDDD;
	border-left: solid 1px #DDDDDD;
	{% endif %}
}
</style>

{% endblock %}

{% block body %}
<div class="container-fluid" style="padding:20px;">
	<div class="row">
		<div class="col-lg-6 col-lg-push-6 col-xs-12">
			<h2 style="margin-top: 0px !important;">Editing a Group{% if group_owner %}<small> (owned by: {% if owner %}me{% else %}{{group_owner}}{% endif %})</small>{% endif %}</h2>
			<p>
				Please add a title and description for this group. Users must first be added to the group by the owner, but can be added by group members if given the appropriate permissions.
			</p>
		</div>
		<div class="col-lg-6 col-lg-pull-6 col-xs-12">
			<form id="group_form" method="POST" action="" >
			{% load crispy_forms_tags %}
			{% crispy form %}
				<hr>
			{% crispy membersform helper %}
				<button type="button" id="addcontrol" {% if not perms.can_add_users and group != None %}disabled{% endif %}>Add User</button>
				<button type="submit">Submit</button>
			</form>
			<table id="empty_form" style="display:none">
				<tbody>
				{% crispy membersform.empty_form trhelper%}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

{% block script %}
<script>
$('#addcontrol').click(function(ev){
	ev.preventDefault();
	var count = $('#controls_container > tbody > tr').length;
	var tmplMarkup = $('#empty_form>tbody').html();
	var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
	$('table#controls_container>tbody').append(compiledTmpl);

	// update form count
	$('#id_member-TOTAL_FORMS').attr('value', count+1);
})
$('th .textInput').each(function(){
	if (!($(this).parents('.form-group').hasClass('has-error'))){
		$(this).prop('readonly', true)
	}
})
$(':checkbox').click(function(){
	if ($(this).prop('readonly')){
		return false
	}
})
var True = true
var False = false
var owner = {{owner|safe}}
console.log('owner', owner)
var perms = {{perms|safe}}
if(perms['can_edit_permissions'] == false){
	$('th input').prop('readonly', true)
	if (perms['can_remove_users'] == true){
		$('th.DELETE input').prop('readonly', false)
	}
}
if (!(owner)){
	$('#id_title, textarea').prop('readonly', true)
}
</script>
{% endblock %}

templates/groups/group_list.html
<ul id="grouptabs" class="nav nav-tabs" role="tablist" style="margin-top:10px;">
		  <li role="presentation" class="active"><a href="#my_groups" aria-controls="my_groups" role="tab" data-toggle="tab">My groups</a></li>
		  <li role="presentation"><a href="#other_groups" aria-controls="other_groups" role="tab" data-toggle="tab">Groups I'm in</a></li>
</ul>
<div id="grouppanes" class="tab-content" style="">
	<div class="input-group" style="padding:20px;">
	  <input type="text" id="my_groups_search" class="form-control" placeholder="search for group title">
	  <span class="input-group-addon"><i class="fa fa-search"></i></span>
	</div>
   {% load slide_tags %}
   <div role="tabpanel" class="tab-pane active" id="my_groups">
   	<div class="row">
   	{% for group in groups %}
   	{% group_item group %}
   	{% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
   	{% endfor %}
   	</div>
   </div>
   <div role="tabpanel" class="tab-pane" id="other_groups">
      <div class="row">
      {% for group in other_groups %}
      {% group_item group %}
      {% if forloop.counter|divisibleby:4 %}<div class="clearfix"></div>{% endif %}
      {% endfor %}
      </div>
   </div>
</div>



<script>
$(function(){
var currentTimeout

 $(document).on('change propertychange keyup', '#my_groups_search', function(){
 	var search = $(this).val().toLowerCase();
 	if (search.length > 3){
 		clearTimeout(currentTimeout);
 		currentTimeout = setTimeout(function(){
 			var thistab = $("#grouppanes div.active")
 			$('.row>.groupItem', thistab).each(function(){
 				if ($(this).data('title').toLowerCase().indexOf(search) > -1){
 					$(this).show()
 				}
 				else {
 					$(this).hide()
 				}
 			})
 		}, 350)
 	}
 	else {
 		var thistab = $("#grouppanes div.active")
 		$('.row>.groupItem', thistab).each(function(){
 			$(this).show()
 			})
 	}
 })
})
</script>

templates/groups/group_list_single.html
<div data-id="{{group.id}}" data-title="{{group.title}}" class="groupItem {% if mode == "use" or mode == "edit"%}col-xs-6 col-sm-4 col-md-3{% else %}col-xs-12{% endif %}">
	<div class="itemContainer itemContainerGroup row">
		<div class="col-xs-12">
			<span class=""><i class="fa fa-users"></i></span>
			<span class="pull-right">
		</div>

		<div class="col-xs-8">
		<div class="col-xs-12{% if mode == "manage"%}{% else %}text-center{% endif %}">
			<h4 style="margin:0; margin-top:5px"><b>{{group.title}}</b>
			<br>
			<small>(by: <span class="owner">{% if group.owner == user %}Me{% else %}{{group.owner.username}}{% endif %}</span>)
			</small>

			</h4>

		</div>
		{% if mode == "manage" %}
			<div class="col-xs-12 itemDescription" style="min-height:100%; margin-top:10px;">
				<p><small></small></p>
				<p>{{group.description}}</p>
			</div>
		</div>
			<div class="col-xs-4">
				<div class="btn-group-vertical btn-block" role="group" aria-label="...">
					<a href="{% url 'view_group' group.id %}" class="btn btn-primary btn-sm">View</a>
					{% if perms.can_add_users == True or perms.can_remove_users == True %}<a href="{% url 'edit_group' group.id %}" class="btn btn-primary btn-sm">Edit</a>{% endif %}
					{% if group.owner == user %}
					<button class="transferbutton btn btn-primary btn-sm" data-itempk="{{group.id}}">Transfer</button>
					{# <a href="{% url 'delete_group' group.id %}" class="btn btn-primary btn-sm">Delete</a> #}
					{% endif %}
				</div>
			</div>
		{% else %}
		</div>
		{% endif %}
		{# The below is unneeded...why would you share a group? just add any user you want to "share" the group with... #}
		<div class="col-xs-12 sharebuttoncontainer">
			{% if perms.can_add_items == True %}
			<button type="button" class=" btn btn-block btn-primary sharegroupbutton">Share</button>
			{% else %}
			<button type="button" class=" btn btn-block btn-primary disabled">Cannot Share</button>
			{% endif %}
		</div>
	</div>
</div>

templates/groups/groups.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Groups' 'groups' %}
{% endblock %}

{% block style %}
<style>
	.tab-content{
		background-color:white;
		border-left:1px solid ddd;
		border-right:1px solid ddd;
		border-bottom:1px solid ddd;
		margin-left: 1px;
	}
	.tab-pane{
		padding:30px;
	}

</style>
{% endblock %}

{% block body %}
<page-header title="Groups" icon="fa-users">
	<a href="{% url 'new_group' %}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> New group</a>
</page-header>
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-4 col-md-5 col-xs-12">
			<info-panel title="You know what a group is">
				Groups allow you to put all the people and objects you need in a single convienient place. This is the alpha test, anybody using this site right now knows exactly what a group is why am I even typing this?
			</info-panel>
		</div>
		<div id="listGroupsLoader" class="col-lg-8 col-md-7 col-xs-12">
		</div>
	</div>
</div>

<div class="modal fade" id="transferModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Transfer Group<span id="sharetitle"></span></h4>
      </div>
      <div id="transferModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="dotransfer" class="btn btn-primary">Transfer Item</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
	$('#listGroupsLoader').load('{% url "list_groups" mode="manage" %}')
	$('#listGroupsLoader').on('click', '.transferbutton', function(){
		$('#transferModalBody').load('/transfer/group/'+$(this).data('itempk')+'/', function(){
			$('#transferModal').modal('show');
		})
	})
</script>
{% endblock %}

templates/groups/sharegroup_template.html
{{form}}