scinage/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
import django_cas_ng.views
import haystack.urls
import layers
from layers import views as views
from layers import dashboard as dashboard
from rest_framework import routers
from layers.api import *

#Register api paths
router = routers.SimpleRouter()
router.register(r'layer', LayerAPIViewset, base_name='layer')

handler404 = layers.views.handler404

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', layers.dashboard.dashboard_all, name="dashboard"),
    url(r'^$', layers.views.frontpage, name="home"),
    url(r'^uploadimage/$', layers.views.ajaximage, name="upload_image"),
    url(r'^uploadvideo/$', layers.views.ajaxvideo, name="upload_video"),

    # Layer Editing
    url(r'^extracontrols/$', layers.views.controlsExtra, name="extra_controls"),
    url(r'^versionfeedback/(?P<version_id>\d+)/$', layers.views.versionFeedback, name="version_feedback"),

    url(r'^widgets/search/', include('haystack.urls')),
    url(r'^widgets/$', layers.views.manageLayers, name="layers"),
    url(r'^widgets/list/(?P<mode>\w+)/$', layers.views.listLayers, name="list_layers"),
    url(r'^widgets/new/$', layers.views.editLayernew, name="new_layer"),
    url(r'^widgets/clone/(?P<layer_id>\d+)/$', layers.views.cloneLayer, name="clone_layer"),
    url(r'^widgets/edit/(?P<layer_id>\d+)/$', layers.views.editLayernew, name="edit_layer"),
    url(r'^widgets/delete/(?P<layer_id>\d+)/$', layers.views.deleteLayer, name="delete_layer"),
    url(r'^widgets/view/(?P<layer_id>\d+)/$', layers.views.editLayer, name="view_layer"),
    url(r'^widgets/editorinput/(?P<id>\d+)/$', layers.views.loadInput),
    url(r'^widgets/favlayer/$', layers.views.toggleLayerFav, name='favlayer'),
    url(r'^widgets/offlayer/$', layers.views.toggleLayerOff, name='offlayer'),
    url(r'^widgets/ratelayer/$', layers.views.layerRating, name='ratelayer'),
    url(r'^widgets/documentation/(?P<version_id>\d+)/$', layers.views.layerDocumentation, name='documentation'),

    url(r'^widgets/newedit/$', layers.views.editLayernew, name="edit_layer_new_new"),
    url(r'^widgets/newedit/(?P<layer_id>\d+)/$', layers.views.editLayernew, name="edit_layer_new"),

    url(r'^widgets/changelog/$', layers.views.changeLog, name="layer_change_log"),

    # Slide Editing
    url(r'^slides/$', layers.views.manageSlides, name="slides"),
    url(r'^slides/list/(?P<mode>\w+)/$', layers.views.listSlides, name="list_slides"),
    url(r'^slides/new/$', layers.views.editSlide, name="new_slide"),
    url(r'^slides/clone/(?P<slide_id>\d+)/$', layers.views.cloneSlide, name="clone_slide"),
    url(r'^slides/edit/(?P<slide_id>\d+)/$', layers.views.editSlide, name="edit_slide"),
    url(r'^slides/delete/(?P<slide_id>\d+)/$', layers.views.deleteSlide, name="delete_slide"),
    url(r'^slides/layersettings/(?P<version_id>\d+)/$', layers.views.layerSettings),
    url(r'^slides/layerjson/new/(?P<version_id>\d+)/$', layers.views.newLayerJson),
    url(r'^slides/layerpreview/$', layers.views.previewLayer),

    # Slide Viewing
    url(r'^slides/view/(?P<slide_id>\d+)/$', layers.views.viewSlide, name="view_slide"),


    # Slideshow Viewing
    url(r'^slideshows/$', layers.views.manageSlideshows, name="slideshows"),
    url(r'^slideshows/list/(?P<mode>\w+)/$', layers.views.listSlideshows, name="list_slideshows"),
    url(r'^slideshows/pdf/upload/$', layers.views.uploadPDF, name="upload_pdf"),
    url(r'^slideshows/pdf/$', layers.views.createSlideshowPDF, name="create_slideshow_from_pdf"),
    url(r'^slideshows/new/$', layers.views.editSlideshow, name="new_slideshow"),
    url(r'^slideshows/clone/(?P<slideshow_id>\d+)/$', layers.views.cloneSlideshow, name="clone_slideshow"),
    url(r'^slideshows/edit/(?P<slideshow_id>\d+)/$', layers.views.editSlideshow, name="edit_slideshow"),
    url(r'^slideshows/delete/(?P<slideshow_id>\d+)/$', layers.views.deleteSlideshow, name="delete_slideshow"),
    url(r'^slideshows/nextslide/(?P<slideshow_id>\d+)/(?P<current_index>\d+)/$', layers.views.nextSlide),
    url(r'^slideshows/view/(?P<slideshow_id>\d+)/$', layers.views.viewSlideshow, name="view_slideshow"),


    # Screen Viewing
    url(r'^screens/$', layers.views.manageScreens, name="screens"),
    url(r'^screens/list/$', layers.views.listScreens, name="list_screens"),
    url(r'^screens/new/$', layers.views.editScreen, name="new_screen"),
    url(r'^screens/edit/(?P<screen_id>\d+)/$', layers.views.editScreen, name="edit_screen"),
    url(r'^screens/delete/(?P<screen_id>\d+)/$', layers.views.editScreen, name="delete_screen"),
    url(r'^screens/view/(?P<slug>[-\w\d]+)/$', layers.views.viewScreen, name="view_screen"),
    url(r'^screens/view/(?P<slug>\d]+)/$', layers.views.viewScreen, name='view_screen_id'),
    url(r'^screens/ping/(?P<slug>[-\w\d]+)/$', layers.views.pingScreen, name="ping_screen"),



    # Group stuff
    url(r'^groups/$', layers.views.manageGroups, name="groups"),
    url(r'^groups/list/(?P<mode>\w+)/$', layers.views.listGroups, name="list_groups"),
    url(r'^groups/new/$', layers.views.editGroup, name="new_group"),
    url(r'^groups/edit/(?P<group_id>\d+)/$', layers.views.editGroup, name="edit_group"),
    url(r'^groups/view/(?P<group_id>\d+)/$', layers.views.viewGroup, name="view_group"),
    url(r'^groups/delete/(?P<group_id>\d+)/$', layers.views.editGroup, name="delete_group"),

    #Images
    url(r'^images/$', layers.views.images, name="images"),
    url(r'^image-upload/$', layers.views.imageUpload, name="image_upload"),
    url(r'^images/delete/(?P<id>[0-9]+)/$', layers.views.deleteImage, name="image_delete"),

    #Videos
    url(r'^videos/$', layers.views.videos, name="videos"),
    url(r'^video-upload/$', layers.views.videoUpload, name="video_upload"),
    url(r'^videos/delete/(?P<id>[0-9]+)/$', layers.views.deleteVideo, name="video_delete"),

    # Sharing
    url(r'^share/(?P<item>\w+)/(?P<pk>\d+)/$', layers.views.shareSettings, name="sharesettings"),
    url(r'^transfer/(?P<item>\w+)/(?P<pk>\d+)/$', layers.views.transferOwnership, name="transfer"),

    #trashbin
    url(r'^trashbin/$', layers.views.trashbin, name='trashbin'),
    url(r'^trashbin/delete/(?P<model>\w+)/(?P<id>[0-9]+)/$', layers.views.delete, name='delete'),
    url(r'^trashbin/restore/(?P<model>\w+)/(?P<id>[0-9]+)/$', layers.views.restore, name='restore'),

    #API routes
    # url(r'^api/', include(router.urls, namespace="api")),

]

from django.conf import settings

# Handling authentication routes

# We want to have the option for a CAS (Central Authentication System) to be configured

# We check for the prescene of a CAS_SERVER_URL in settings
# If it is present we will authenticate through that CAS Server
# Likewise, if it's not then we will use our own authentication system
if settings.CAS_SERVER_URL is not None:
    urlpatterns.extend([
        url(r'^accounts/login/$', django_cas_ng.views.LoginView.as_view(), name='login'),
        url(r'^accounts/logout/$', django_cas_ng.views.LogoutView.as_view(), name='logout')
    ])
else:
    urlpatterns.extend([
        url(r'^accounts/signup/$', layers.views.SignUp.as_view(), name='signup'),
        url('^', include('django.contrib.auth.urls')),
        # url(r'^accounts/password_reset/$', layers.views.PasswordReset.as_view(), name='password_reset'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
    ])

from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/media/', document_root=settings.MEDIA_ROOT)

layers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, ValidationError, MaxValueValidator, MinValueValidator

from django.db.models.deletion import Collector
from django.db.models.fields.related import ForeignKey

from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit, ResizeToFill

from taggit.managers import TaggableManager
from haystack import signals

# Trashbin imports
from django.utils.translation import ugettext_lazy as _
try:
    from django.utils import timezone as datetime
except ImportError:
    from datetime import datetime

# Template Rendering with jinja
from jinja2 import Template

from .managers import *

# Input stuff
from .InputList import *


# For setting min max values on integerfields
class IntegerRangeField(models.IntegerField):
    def __init__(
        self,
        verbose_name=None,
        name=None,
        min_value=None,
        max_value=None,
        **kwargs
    ):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


# django-undelete models fixed
class TrashableMixin(models.Model):
    trashed_at = models.DateTimeField(
        _('Trashed'),
        editable=False,
        blank=True,
        null=True
    )

    objects = NonTrashedManager()
    trash = TrashedManager()
    everything = models.Manager()

    def delete(self, *args, **kwargs):
        # keyword argument trash has default value True
        trash = kwargs.get('trash', True)
        if not self.trashed_at and trash:
            self.trashed_at = datetime.now()
            self.save()
        else:
            super(TrashableMixin, self).delete(*args, **kwargs)

    def restore(self, commit=True):
        self.trashed_at = None
        if commit:
            self.save()

    class Meta:
        abstract = True


"""
When a user creates a new layer, it will create a version to go with it.
Anytime a user wants to change what their layer looks like, it will create a
new version for the revision, and (if it is not shared) offer to delete
older versions.

A version is simply a list of input types and the jinja2(?) html code to render
the object

Input types will each contain html / css / js to add an extra field for users
to fill in.
We'll have colorpickers and shit.
"""
variable = RegexValidator(
    r'^[a-zA-Z]{1}[0-9a-zA-Z_]*$',
    'Only alphanumeric characters are allowed. Must start with a letter.',
)


class UploadedImage(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(
        upload_to='uploaded_images',
        processors=[ResizeToFit(1920, 1080, False)],
        format='PNG',
        options={'quality': 80}
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFit(100, 100)],
        format='JPEG',
        options={'quality': 60}
    )


class UploadedVideo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    video = models.FileField(
        upload_to='uploaded_videos',
    )
    # title = models.CharField(max_length=255, blank=True)
    # thumbnail = ImageSpecField(
    #     source='video',
    #     processors=[ResizeToFit(100, 100)],
    #     format='JPEG',
    #     options={'quality': 60}
    # )


class Layer(TrashableMixin):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    shared = models.BooleanField(default=False)
    official = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    short = models.CharField(max_length=12)
    description = models.TextField()
    tags = TaggableManager()
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)
    documentation = models.TextField(blank=True)

    # tags
    icon = ProcessedImageField(
        upload_to='icons',
        processors=[ResizeToFit(72, 72)],
        format='PNG',
        options={'quality': 80},
        blank=True, null=True
    )

    def bleeding_edge(self):
        pass

    def latest(self):
        try:
            return self.version_set.filter(publish=True).order_by(
                '-creation_date'
            )[0:1].get()
        except:
            return self.version_set.order_by('-creation_date')[0:1].get()

    def uses(self):
        return SlideLayer.objects.filter(version__layer=self).count()

    def get_slides(self):
        return SlideLayer.objects.filter(version__layer=self).values("slide")

    def favs(self):
        return self.favoritelayer_set.all().count()

    @property
    def rating(self):
        return round(self.layerrating_set.aggregate(
            models.Avg('rating'))['rating__avg'],
            1
        )

    def clone(self, user):
        newlayer = Layer.objects.get(id=self.id)
        newlayer.id = None
        newlayer.public = False
        newlayer.official = False
        newlayer.title = "CLONE OF %s" % self.title
        newlayer.owner = user
        newlayer.publish = False
        newlayer.changes = 'First version.'
        newlayer.shared = False
        newlayer.save()
        for x in self.tags.all():
            newlayer.tags.add(x)
        newlayer.save()
        # And make the version...
        oldversion = self.latest()
        newversion = self.latest()
        newversion.publish = False
        newversion.id = None
        newversion.layer = newlayer
        newversion.save()
        for control in oldversion.control_set.all():
            newcontrol = Control(
                version=newversion,
                title=control.title,
                variable_name=control.variable_name,
                verbose=control.verbose,
                input_type=control.input_type,
                default=control.default
            )
            newcontrol.save()
        return newlayer


class FavoriteLayer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)


class LayerRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    rating = IntegerRangeField(min_value=1, max_value=5)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta():
        unique_together = ('user', 'layer')


class Version(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    content = models.TextField()
    content_css = models.TextField(blank=True)
    content_js = models.TextField(blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, blank=True, null=True)
    changes = models.TextField(blank=True)
    publish = models.BooleanField(default=False)

    # every edit after a publish will be a new version!

    last_edit = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='version_last_edit',
        on_delete=models.CASCADE
    )

    def save(self, publish=False, *args, **kwargs):
        if self.layer.version_set.all().count() == 0:
            new_layer = True
        else:
            new_layer = False

        super(Version, self).save(*args, **kwargs)
        if publish is True and new_layer is False:
            # We're going to do this by hand because stackoverflow only has
            # answers for ancient versions of django and I spent too bloody
            # long trying to write a general duplicator and got only nonsense
            # error messages
            # Duplicate the object to make a new HEAD version.
            new = Version(
                layer=self.layer,
                content=self.content,
                content_css=self.content_css,
                content_js=self.content_js
            )
            new.save()
            # Get all the controls too
            for control in self.control_set.all():
                newcontrol = Control(
                    version=new,
                    title=control.title,
                    variable_name=control.variable_name,
                    verbose=control.verbose,
                    input_type=control.input_type,
                    default=control.default
                )
                newcontrol.save()

    def updateAvailable(self):
        return self.layer.version_set.filter(
            creation_date__gt=self.creation_date,
            publish=True
        ).order_by('-creation_date').first()

    def compileContent(self, data=None):
        from helpers.extra import extra_globals
        compiled = """
            <html>
                <head>
                    <style>
                        %s
                    </style>
                </head>
                <body>
                    %s
                    <script>
                        window.$ = $ || window.top.$
                        parent.iframeCheck()
                        $(window).on('load', function(){
                          parent.iframeCheck(true)
                        })
                    </script>
                    <script>

                        %s
                    </script>
                </body>
            </html>
        """ % (self.content_css, self.content, self.content_js)
        template = Template(compiled)
        template.globals.update(extra_globals)

        if not data:

templates/layers/editlayer.html
{% extends 'UI/skin.html' %}
{% load breadcrumbs %}

{% block breadcrumbs %}
{% breadcrumb_url 'Layers' 'layers' %}
	{% if layer != None %}
	{% with "Edit: "|add:layer.title as current %}
		{% breadcrumb current %}
	{% endwith %}
	{% else %}
    {% breadcrumb 'New Layer' %}
    {% endif %}
{% endblock %}

{% block style %}
	<style>
		body{
			padding: 0;
			margin: 0;
		}
		#layersettings{
			padding-top:55px;
			width: 50%;
			height: 100%;
			overflow-y: scroll;
			position: absolute;
			left: 0;
			top:0;
			background-color: #E6E6E6;
		}
		#preview-holder{
			padding-top:65px;
			padding-left:15px;
			width: 50%;
			height: 100%;
			position: absolute;
			right: 0;
			top:0;
			background-color: #373d47;
		}
		#preview{
			background: #474d57;
			outline: 3px solid white;
			overflow: hidden;
			resize: both;
			width: 100%;
			height: 300px;
			min-width: 300px;
			min-height: 150px;
			max-width: 40vw;
			max-height: 80vh;
		}
		#controls{
			width: 100%;
		}
		.ui-sidebar-wrapper{
			height:100vh;
		}
	</style>
{% endblock %}

{% block body %}
	<div id="layersettings">
	<div class="col-xs-12">
		<br>
		<form id="controls_form" method="POST" action="/layers/preview/" enctype="multipart/form-data">
		{% load crispy_forms_tags %}

		{% crispy layerform %}
		{% crispy versionform %}
		<button type="button" id="preview-button">Preview</button>
		<button type="button" id="submit-button">Submit</button>
		{% crispy controlsform helper %}
		<table id="empty_form" style="display:none">
			<tbody>
                {% crispy controlsform.empty_form trhelper%}
      </tbody>
		</table>
		<button type="button" id="addcontrol">Add Control</button>
		</form>
	</div>
	</div>

	<div id="preview-holder">
		<iframe name="preview_frame" id="preview" width="160px" height="120px" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0">>
		</iframe>
	</div>


 <div id="controls-extra">
 </div>

{% endblock %}
{% block script %}

	<script>

		$(function(){
			var doc = $("#preview")[0].contentWindow.document;
			var body = $('body',doc);
			body.html({{preview|safe}})
			$( "#preview" ).draggable({
			  containment: "parent"
			});

			$("#controls-extra").load('{% url 'extra_controls' %}')
			$('#preview-button').click(function(ev){
				{% if layer != None %}
				$('#controls_form').attr('action', '/layers/edit/{{layer.id}}/?preview=True').attr('target', 'preview_frame').submit()
				{% else %}
				$('#controls_form').attr('action', '/layers/new/?preview=True').attr('target', 'preview_frame').submit();
				{% endif %}
			})
			$('#submit-button').click(function(ev){
				{% if layer != None %}
				$('#controls_form').attr('action', '/layers/edit/{{layer.id}}/').attr('target', '').submit()
				{% else %}
				$('#controls_form').attr('action', '/layers/new/').attr('target', '').submit();
				{% endif %}
			})
			$('#id_publish').click (function(){
			  var thisCheck = $(this);

			  if ( thisCheck.is(':checked') ) {
			  	$("#changesmodal").modal({'show': true})
			    
			  }
			});
			// Change default input html when changing thingies
			$('#controls').on('change', '.type', function(ev){
				var row = $(this).closest('tr')
				row.find('.defaultinput').load('/layers/editorinput/'+$(this).val())
			})

			$('#addcontrol').click(function(ev){
						ev.preventDefault();
						var count = $('#controls_container > tbody > tr').length;
						var tmplMarkup = $('#empty_form>tbody').html();
						var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
						$('table#controls_container>tbody').append(compiledTmpl);

						// update form count
						$('#id_controls-TOTAL_FORMS').attr('value', count+1);
					})

		})
	</script>
{% endblock %}

templates/layers/extra_control_selectors.html
{% load slide_tags %}

<!-- Image Modal -->
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="imageModalLabel">Select or Upload Image</h4>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <input id="image_select_url" type="text" class="form-control" placeholder="URL Here">
          <span class="input-group-btn">
            <button id="image_select_ok" class="btn btn-success" type="button">OK</button>
          </span>
        </div><!-- /input-group -->
      	<input id="image_upload" type="file" class="form-control">
      	<table class="table">
      	<tbody id="image_list">
      		{% for image in images %}
            {% if image.image %}
      			<tr>
      				<td class="text-center"><img src="{{image.thumbnail.url}}" class="modal-thumbnails"></td>
              <td>
        				<p><small>{{image.creation_date}}</small></p>
        				<p><small class="image_url" data-url="{{request.scheme}}://{{request.get_host}}{{image.image.url}}">{{image.image.url|url_short}}</small></p>
      				</td>
      			</tr>
            {% endif %}
      		{% endfor %}
      	</tbody>
      	</table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
<!-- Video Modal -->
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="videoModalLabel">Select or Upload Video</h4>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <input id="video_select_url" type="text" class="form-control" placeholder="URL Here">
          <span class="input-group-btn">
            <button id="video_select_ok" class="btn btn-success" type="button">OK</button>
          </span>
        </div><!-- /input-group -->
        <input id="video_upload" type="file" class="form-control">
        <table class="table">
        <tbody id="video_list">
          {% for video in videos %}
            {% if video.video %}
            <tr>
              <td class="text-center"><img src="{{video.thumbnail.url}}" class="modal-thumbnails"></td>
              <td>
                <p><small>{{video.creation_date}}</small></p>
                <p><small class="video_url" data-url="{{request.scheme}}://{{request.get_host}}{{video.video.url}}">{{video.video.url|url_short}}</small></p>
              </td>
            </tr>
            {% endif %}
          {% endfor %}
        </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>


  <script>
  var selected_default;
  $(function(){
    $('#controls_container').on('click', '.textInput[name$="default"]', function(){
      selected_default = $(this);
      var val = $(this).closest('tr').find('.select[name$="input_type"] option:selected').text()
      if (val == 'Image'){
        $('#imageModal').modal('show');
      }
      else if (val == 'Video'){
        $('#videoModal').modal('show');
      }
    })
    // Image
    $('#layersettings').on('click', '.image-select-input', function(){
      selected_default = $(this);
      $('#imageModal').modal('show');
    })
    $("#image_upload").on('change' ,function(){
      var image = $('#image_upload')[0].files[0];
      data = new FormData();
      data.append('image', image)
      data.append('csrfmiddlewaretoken', '{{ csrf_token }}')
      //POST SELECTED TO /update/id
      $.ajax({
          url: "/uploadimage/",
          data: data,
          processData: false,
          contentType: false,
          type: 'POST',
          dataType:'json',
          success: function(data){
            var newrow = $("<tr></tr>");
            newrow.append('<td class="text-center"><img src="'+data.thumb+'" class="modal-thumbnails"></td>')
            newrow.append('<td><p><small>Just Now</small></p><p><small class="image_url" data-url="{{request.scheme}}://{{request.get_host}}'+data.image+'">'+data.image+'</small></p></td>')
            $("#image_list").prepend(newrow);
            newrow.click()
        }
      })
      $(this).parent().siblings('.displayImage').removeAttr('style')
      var item = $(this).attr('name')
      var icon = $("#" + item + "image")
      icon.css({"display":"inline"})
    })
    $("#image_list").on('click', 'tr', function(){
      $('#image_select_url').val($(this).find('.image_url').data('url'));
      $('#image_select_ok').click();
    })
    $("#image_select_ok").click(function(){
      selected_default.val($('#image_select_url').val());
      selected_default.change();
      $('#imageModal').modal('hide');
    })
    // Video
    $('#layersettings').on('click', '.video-select-input', function(){
      selected_default = $(this);
      $('#videoModal').modal('show');
    })
    $("#video_upload").on('change' ,function(){
      var video = $('#video_upload')[0].files[0];
      data = new FormData();
      data.append('video', video)
      data.append('csrfmiddlewaretoken', '{{ csrf_token }}')
      //POST SELECTED TO /update/id
      $.ajax({
          url: "/uploadvideo/",
          data: data,
          processData: false,
          contentType: false,
          type: 'POST',
          dataType:'json',
          success: function(data){
            var newrow = $("<tr></tr>");
            newrow.append('<td class="text-center"><img src="'+data.thumb+'" class="modal-thumbnails"></td>')
            newrow.append('<td><p><small>Just Now</small></p><p><small class="video_url" data-url="{{request.scheme}}://{{request.get_host}}'+data.video+'">'+data.video+'</small></p></td>')
            $("#video_list").prepend(newrow);
            newrow.click()
        }
      })
      $(this).parent().siblings('.displayVideo').removeAttr('style')
      var item = $(this).attr('name')
      var icon = $("#" + item + "video")
      icon.css({"display":"inline"})
    })
    $("#video_list").on('click', 'tr', function(){
      $('#video_select_url').val($(this).find('.video_url').data('url'));
      $('#video_select_ok').click();
    })
    $("#video_select_ok").click(function(){
      selected_default.val($('#video_select_url').val());
      selected_default.change();
      $('#videoModal').modal('hide');
    })
  })
  </script>